Added functions and applications settings for Bash

diff --git a/dot_bashrc.tmpl b/dot_bashrc.tmpl
--- a/dot_bashrc.tmpl
+++ b/dot_bashrc.tmpl
@@ -194,6 +194,25 @@ path-remove-duplicates () {
 	return $RETURN_VALUE
 }
 
+swap () {
+	is-true "$DEBUG" && enable-xtrace
+
+	if [[ ! $# -eq 2 ]]
+	then
+		echo "Usage: $0 file1 file2"
+		echo "Example: $0 /etc/resolv.conf resolv.new"
+		return 1
+	fi
+
+	local TMPFILE="tmp.$$"
+	mv "$1" "$TMPFILE"
+	mv "$2" "$1"
+	mv "$TMPFILE" "$2"
+
+	local RETURN_VALUE=$?
+	is-true "$DEBUG" && disable-xtrace
+	return $RETURN_VALUE
+}
 
 ########################################
 # Pre-flight operations.
@@ -326,3 +345,115 @@ ask-for-confirmation () {
 	is-true "$DEBUG" && disable-xtrace
 	return $RETURN_VALUE
 }
+
+{{-    if and
+         (lookPath "lynx")
+         (lookPath "pandoc") }}
+
+# Show a rendered markdown file.
+alias mdv='markdown-view'
+markdown-view () {
+	is-true "$DEBUG" && enable-xtrace
+
+	if [[ $# -lt 1 ]]
+	then
+		echo "error: no input files given" >&2
+		echo "usage: $0 FILE..."
+		return 1
+	fi
+
+	pandoc $@ | lynx -stdin
+
+	local RETURN_VALUE=$?
+	is-true "$DEBUG" && disable-xtrace
+	return $RETURN_VALUE
+}
+
+{{-    end }}
+
+####################
+# Table flipping.
+#
+# https://cutekaomoji.com/misc/table-flipping/
+####################
+
+table_flips=(
+	'(╯°□°）╯︵ ┻━┻'
+	'(┛◉Д◉)┛彡┻━┻'
+	'(ﾉ≧∇≦)ﾉ ﾐ ┸━┸'
+	'(ノಠ益ಠ)ノ彡┻━┻'
+	'(╯ರ ~ ರ）╯︵ ┻━┻'
+	'(┛ಸ_ಸ)┛彡┻━┻'
+	'(ﾉ´･ω･)ﾉ ﾐ ┸━┸'
+	'(ノಥ,_｣ಥ)ノ彡┻━┻'
+	'(┛✧Д✧))┛彡┻━┻'
+	'┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻'
+	'┻━┻ ︵ ¯\(ツ)/¯ ︵ ┻━┻'
+	'(ノTДT)ノ ┫:･’.::･┻┻:･’.::･'
+	'(ノ｀⌒´)ノ ┫：・’.：：・┻┻：・’.：：・'
+	'(ﾉ*｀▽´*)ﾉ ⌒┫ ┻ ┣ ┳'
+	'┻━┻ミ＼(≧ﾛ≦＼)'
+	'┻━┻︵└(՞▃՞ └)'
+	'┻━┻︵└(´▃｀└)'
+	'─=≡Σ((((╯°□°）╯︵ ┻━┻'
+	'(ノ｀´)ノ ~┻━┻'
+	'(-_- )ﾉ⌒┫ ┻ ┣'
+	'(ノ￣皿￣）ノ ⌒=== ┫'
+	'ノ｀⌒´)ノ ┫：・’.：：・┻┻'
+	'༼ﾉຈل͜ຈ༽ﾉ︵┻━┻'
+	'ヽ༼ຈل͜ຈ༽ﾉ⌒┫ ┻ ┣'
+	'ﾐ┻┻(ﾉ>｡<)ﾉ'
+	'.::･┻┻☆()ﾟOﾟ)'
+	'(ノʘ言ʘ)ﾉ ⌒┫ ┻ ┣ ┳☆(>｡☆)'
+	'(ノ｀m´)ノ ~┻━┻ (/o＼)'
+	'(ﾉ≧∇≦)ﾉ ﾐ ┸┸)`νﾟ)･;’.'
+	'ミ(ノ￣^￣)ノ≡≡≡≡≡━┳━☆()￣□￣)/'
+)
+
+table_sets=(
+	'┣ﾍ(^▽^ﾍ)Ξ(ﾟ▽ﾟ*)ﾉ┳━┳'
+	'┬──┬ ノ( ゜-゜ノ)'
+	'┬──┬ ¯\_(ツ)'
+	'(ヘ･_･)ヘ┳━┳'
+	'ヘ(´° □°)ヘ┳━┳'
+	'┣ﾍ(≧∇≦ﾍ)… (≧∇≦)/┳━┳'
+	'(つ ์ 𓎟 ์ )つ┳━┳'
+	'(੭່˙ ์•͈ ▿ •͈ ์ )੭່˙┬──┬'
+)
+
+alias table-flip-random='shuf -e "${table_flips[@]}" | head -n 1'
+alias table-set-random='shuf -e "${table_sets[@]}" | head -n 1'
+
+alias flip-table="echo '(╯°□°)╯︵ ┻━┻'"
+alias look-of-disapproval="echo 'ಠ_ಠ'"
+alias middle-finger="echo 't(-.-t)'"
+alias shrug="echo '¯\_(ツ)_/¯'"
+alias y-u-no="echo 'ლ(ಠ益ಠლ)'"
+
+########################################
+# Helpers.
+########################################
+
+# Enable the recording of system upgrade routines for ease of use.
+if [[ -z "${UPGRADE_ROUTINES[@]}" ]]
+then
+	UPGRADE_ROUTINES=()
+fi
+
+########################################
+# Applications settings.
+########################################
+
+{{-    $editor := coalesce
+         (dig "editor" "" .)
+		 (lookPath "vim")
+		 (lookPath "vim.tiny")
+		 (lookPath "nano")
+		 (lookPath "vi")
+		 (env "EDITOR") }}
+{{-    if $editor }}
+
+# Set the default editor.
+export EDITOR={{ $editor | quote }}
+
+{{-    end }}
