Added to-lower and ask-for-confirmation functions

diff --git a/dot_bashrc.tmpl b/dot_bashrc.tmpl
--- a/dot_bashrc.tmpl
+++ b/dot_bashrc.tmpl
@@ -65,24 +65,23 @@ is-shell-login () {
 
 # Needs to return 0 or 1 and not `true` or `false`.
 # Input's case is lowered to save on match options.
+is-true () {
+	local LOWERED_INPUT="$(to-lower "$1")"
+	if [[ ! "$LOWERED_INPUT" =~ ^1|on|true|yes$ ]]
+	then
+		return 1
+	fi
+}
+
+to-lower () {
 {{- /* The shortened version is available since Bash 5. */}}
 {{-    if lt (atoi (output "bash" "-c" "echo ${BASH_VERSION:0:1}" | trim)) 5 }}
-# Bash3 has no built-in means to convert case of a string, fallback to `tr`.
-is-true () {
-	local INPUT="$(echo "$1" | tr '[:upper:]' '[:lower:]')"
-	if [[ ! "$INPUT" =~ ^1|on|true|yes$ ]]
-	then
-		return 1
-	fi
-}
+	# Bash3 has no built-in means to convert case of a string, fallback to `tr`.
+	echo "$(echo "$1" | tr '[:upper:]' '[:lower:]')"
 {{-    else }}
-is-true () {
-	if [[ ! "${1,,}" =~ ^1|on|true|yes$ ]]
-	then
-		return 1
-	fi
-}
+	echo "${1,,}"
 {{-    end }}
+}
 
 ########################################
 # Pre-flight checks.
@@ -174,3 +173,19 @@ alias please='sudo'
 alias sedo='sudo redo'
 
 {{-    end }}
+
+ask-for-confirmation () {
+	is-true "$DEBUG" && enable-xtrace
+
+	read -p 'Continue? ' REPLY
+
+	if ! is-true "$REPLY"
+	then
+		echo "aborting"
+		return 1
+	fi
+
+	local RETURN_VALUE=$?
+	is-true "$DEBUG" && disable-xtrace
+	return $RETURN_VALUE
+}
